sudo: false
dist: xenial

services:
  - mongodb
  - redis
  - mysql
os:
  - linux
language: python

python:
  - "3.7"

install:
  - pip install tox-travis

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script:
  - tox
