sudo: false
dist: xenial

services:
  - mongodb
  - redis
  - mysql
os:
  - linux
language: python

python:
  - "3.7"

install:
  - pip install tox-travis

before_script:
  - mysql -e 'create database testdb DEFAULT CHARACTER SET utf8mb4;'

script:
  - tox
